CREATE TABLE USER (
	id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	username VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(128) NOT NULL,
	salt VARCHAR(100) NOT NULL,
	admin BOOLEAN NOT NULL,
	registerTime BIGINT NOT NULL,
	lastLoginTime BIGINT NOT NULL,
	lastModifiedTime BIGINT NOT NULL
);